services:

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_dev:/data/db
    ports:
      - "27017:27017"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_dev
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=HomeMaidOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
    volumes:
      - influxdb_dev_data:/var/lib/influxdb2

volumes:
  mongodb_dev:
  influxdb_dev_data:
